self_search: true ## Use a jQuery-based local search engine, true/false.
google_site_verification: Ph4uk9e5fGoV3rSFMpdNoNZJBSHxWsmVKl5ednytzrg
baidu_site_verification: 8C4DGZbWaD
baidu_tongji: ## d603ef9eb2133726e8012c331f1b7683
show_category_count: false ## If you want to show the count of categories in the sidebar widget please set the value to true.
busuanzi: false ## If you want to use Busuanzi page views please set the value to true.
widgets_on_small_screens: false ## Set to true to enable widgets on small screens.

menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user

widgets: ## Six widgets in sidebar provided: search, category, tag, recent_posts, rencent_comments and links.
  - search
  - category
  - tag
  - recent_posts
  - links

links:
  - title: BAOTING ART
    url: http://www.baotingart.com/

timeline:
  - num: 1
    word: 2014/06/12-Start
  - num: 2
    word: 2014/11/29-XXX
  - num: 3
    word: 2015/02/18-DDD
  - num: 4
    word: More

comments:
  gentie_key: b9fd8bda2b414523aa194e154da4b8ac

toc:
    max_depth: 3
    
# Static files
js: js
css: css

# Theme version
version: 0.0.2
